language: node_js
node_js: '0.10'
sudo: false
script: npm run build
deploy:
- provider: divshot
  api_key:
    secure: fp7WGhALw04OM3KMYkNKj1iKFp2LweWjdkZh+bprUh/1S6nk6bRlb17GANUuTc/UaQidJpdc+qp93OVBVE+042WiOp2/nc64xxyuPgiv2CGd2+lBcoZzIq2TXTTbwd4NM748tTDy+o89RudxUNb9CfcNLKu+NqWhP0dP7wht5Ng=
  environment: production
  on:
    branch: master
  skip_cleanup: true
notifications:
  slack:
    secure: N6FbQmqGrqq3qZucvLZRAZskS/10Yss1MfSPfhGAgDLP+4GvKSZL0EE60HZABFvjj8DjJggBSTBHN6uOrOHtbeuPbCIIfbkZtLD16nMNXxC7ll0G0dk62Yzhx9N39edzNFupPX9DOkQahXxKDLC4LlsfTkVmswgKMKBdvalnMZI=
