language: node_js
node_js: '0.10'
before_script:
- npm install -g bower
- bower install
script: npm run build
after_deploy: sh ./scripts/deliver.sh
deploy:
- provider: divshot
  api_key:
    secure: fp7WGhALw04OM3KMYkNKj1iKFp2LweWjdkZh+bprUh/1S6nk6bRlb17GANUuTc/UaQidJpdc+qp93OVBVE+042WiOp2/nc64xxyuPgiv2CGd2+lBcoZzIq2TXTTbwd4NM748tTDy+o89RudxUNb9CfcNLKu+NqWhP0dP7wht5Ng=
  environment: development
  on: develop
  skip_cleanup: true
- provider: divshot
  api_key:
    secure: fp7WGhALw04OM3KMYkNKj1iKFp2LweWjdkZh+bprUh/1S6nk6bRlb17GANUuTc/UaQidJpdc+qp93OVBVE+042WiOp2/nc64xxyuPgiv2CGd2+lBcoZzIq2TXTTbwd4NM748tTDy+o89RudxUNb9CfcNLKu+NqWhP0dP7wht5Ng=
  environment: staging
  on: master
  skip_cleanup: true
- provider: divshot
  api_key:
    secure: fp7WGhALw04OM3KMYkNKj1iKFp2LweWjdkZh+bprUh/1S6nk6bRlb17GANUuTc/UaQidJpdc+qp93OVBVE+042WiOp2/nc64xxyuPgiv2CGd2+lBcoZzIq2TXTTbwd4NM748tTDy+o89RudxUNb9CfcNLKu+NqWhP0dP7wht5Ng=
  environment: production
  on:
    branch: master
    tags: true
  skip_cleanup: true
notifications:
  slack:
    secure: N6FbQmqGrqq3qZucvLZRAZskS/10Yss1MfSPfhGAgDLP+4GvKSZL0EE60HZABFvjj8DjJggBSTBHN6uOrOHtbeuPbCIIfbkZtLD16nMNXxC7ll0G0dk62Yzhx9N39edzNFupPX9DOkQahXxKDLC4LlsfTkVmswgKMKBdvalnMZI=
env:
  global:
  - TRACKER_PROJECT_ID=1109168
  - secure: i0+Uih588vlMy6TTNX2Qit4XA4aoIDQXZ4t9uftAXXmejj1S8ae1exQe+swWH2ojEbHSI50MMkfida8ezSrhAVYAca8RTG8lw4MMlTZKEIe9NVnWsCAhtmNTQzo9rL1+kX4I1WC1lzNiJyLOQgMnc00SBK+3eBqFcYSTBjWKNAw=
