# TODO: explain it
name: Valet.io

# TODO: explain it
# subdomain: sample

# TODO: explain it
domains: [www.valet.io]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: Valet.io | Make Every Event a Fundraiser | Mobile Pledge and Silent Auction
meta_keywords: "mobile fundraising, mobile pledge, silent auction, charity gala, political campaigns"
meta_description: "Turn any event into a fundraiser with Valet.io's seamless mobile pledge drive and bidding tools. Guests use their own smartphones and no downloads are ever required."